from datetime import datetime,timedelta,timezone
print(datetime.now())
dt = datetime(2018,5,25,15,20)
print(dt)
ts = dt.timestamp()
print(ts)
date = datetime.fromtimestamp(ts)
print(date)
print(datetime.utcfromtimestamp(datetime.now().timestamp()))
print ('-------------------------------------------------------')

cday = datetime.strptime('2018/07/12 19:20:33','%Y/%m/%d %H:%M:%S')
print(cday)
print(datetime.utcfromtimestamp(cday.timestamp()))
print ('-------------------------------------------------------')

print(datetime.now().strftime('%A,%B,%d,%H:%M'))
print ('-------------------------------------------------------')

now = datetime.now()
print(now)
print(now + timedelta(hours=23))
print(now + timedelta(days=1,hours=2))
print ('-------------------------------------------------------')
tz_utc_8 = timezone(timedelta(hours=8))
print(now)
d = now.replace(tzinfo=tz_utc_8)
print(d)
print(d.timestamp())
m = now.replace(tzinfo=timezone(timedelta(hours=2)))
print(m)
print(m.timestamp())
print ('-------------------------------------------------------')
utc_dt = datetime.utcnow().replace(tzinfo=timezone.utc)
print(datetime.utcnow())
print(utc_dt)
bj_dt = utc_dt.astimezone(timezone(timedelta(hours=8)))
print(bj_dt)
tokyo_dt = utc_dt.astimezone(timezone(timedelta(hours=9)))
print(tokyo_dt)
tokyo_dt2 = bj_dt.astimezone(timezone(timedelta(hours=9)))
print(tokyo_dt2)
print ('-------------------------------------------------------')

dt2_str = '2018-5-24 15:12:34'
dt2 = datetime.strptime(dt2_str,'%Y-%m-%d %H:%M:%S')
dt2_utc = dt2.replace(tzinfo=timezone(timedelta(hours=8)))
dt3_utc = dt2.replace(tzinfo=timezone(timedelta(hours=7)))
print(dt2_utc.timestamp())
print(dt3_utc.timestamp())